pipeline {
    agent any

    tools {
        nodejs "Node"   // This must match your Jenkins global config name
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/GourishSavant/RProject.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }

        stage('Run Tests') {
            steps {
                sh 'npm test || echo "Tests skipped"'
            }
        }

        stage('Build Project') {
            steps {
                sh 'npm run build || echo "No build script defined"'
            }
        }

        stage('Deploy (Optional)') {
            steps {
                sh 'pm2 restart server.js || pm2 start server.js --name node-app'
            }
        }
    }
}


